In [1]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA
from sklearn.pipeline import Pipeline
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier

from sklearn.svm import SVC

from xgboost import XGBClassifier

In [2]:
data=pd.read_csv("new_updated_coordinate.csv")
data1=pd.read_csv('test_purpose.csv')
data

,pgNo,startX,startY,endX,endY,w,h,fntSize,txtColor,txtFnt,...,top_txtColor,top_txtFnt,top_topMargin,top_bottomMargin,top_leftMargin,top_rightMargin,top_wordPosition,top_txt,txt,label
0,1,74.85,69.78,158.84,80.26,83.99,10.48,14.6832,-16777216,BookmanOldStyle-Bold,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,ALSECURE,Name
1,1,163.85,69.78,175.59,80.26,11.74,10.48,14.6832,-16777216,BookmanOldStyle-Bold,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,&,Name
2,1,180.53,69.78,283.82,80.26,103.29,10.48,14.6832,-16777216,BookmanOldStyle-Bold,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,PROTECTION,Name
3,1,288.77,69.78,368.10,80.26,79.33,10.48,14.6832,-16777216,BookmanOldStyle-Bold,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,SERVICES,Name
4,1,378.07,69.78,432.12,80.26,54.05,10.48,14.6832,-16777216,BookmanOldStyle-Bold,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,(INDIA),Name
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1982,1,395.44,1515.38,438.81,1521.02,43.37,5.64,9.7500,-16777216,Helvetica,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,68243000,NaN
1983,1,441.52,1515.38,460.49,1521.02,18.97,5.64,9.7500,-16777216,Helvetica,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Fax:,NaN
1984,1,463.20,1515.38,494.62,1521.02,31.42,5.64,9.7500,-16777216,Helvetica,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,(91-80),NaN
1985,1,497.33,1515.38,540.70,1521.02,43.37,5.64,9.7500,-16777216,Helvetica,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,68243001,NaN
1986,1,543.41,1515.38,633.34,1521.02,89.93,5.64,9.7500,-16777216,Helvetica,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,www.teamlease.com,NaN

In [3]:
data1.shape

(621, 82)

In [4]:
data.shape

(1987, 83)

In [5]:
data1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 621 entries, 0 to 620
Data columns (total 82 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   pgNo                 621 non-null    int64
 1   startX               621 non-null    float64
 2   startY               621 non-null    float64
 3   endX                 621 non-null    float64
 4   endY                 621 non-null    float64
 5   w                    621 non-null    float64
 6   h                    621 non-null    float64
 7   fntSize              621 non-null    float64
 8   txtColor             621 non-null    int64
 9   txtFnt               621 non-null    object
 10  docName              621 non-null    object
 11  pgW                  621 non-null    int64
 12  pgH                  621 non-null    int64
 13  topMargin            621 non-null    float64
 14  bottomMargin         621 non-null    float64
 15  leftMargin           621 non-null    float64
 16  rightMargin          621 non-null    float64
 17  lSize                621 non-null    int64
 18  lnNo                 621 non-null    int64
 19  lWhiteSpaces         621 non-null    int64
 20  wordPosition         621 non-null    int64
 21  left_startX          528 non-null    float64
 22  left_startY          528 non-null    float64
 23  left_endX            528 non-null    float64
 24  left_endY            528 non-null    float64
 25  left_w               528 non-null    float64
 26  left_h               528 non-null    float64
 27  left_fntSize         528 non-null    float64
 28  left_txtColor        528 non-null    float64
 29  left_txtFnt          528 non-null    object
 30  left_topMargin       528 non-null    float64
 31  left_bottomMargin    528 non-null    float64
 32  left_leftMargin      528 non-null    float64
 33  left_rightMargin     528 non-null    float64
 34  left_wordPosition    528 non-null    float64
 35  left_txt             528 non-null    object
 36  right_startX         528 non-null    float64
 37  right_startY         528 non-null    float64
 38  right_endX           528 non-null    float64
 39  right_endY           528 non-null    float64
 40  right_w              528 non-null    float64
 41  right_h              528 non-null    float64
 42  right_fntSize        528 non-null    float64
 43  right_txtColor       528 non-null    float64
 44  right_txtFnt         528 non-null    object
 45  right_topMargin      528 non-null    float64
 46  right_bottomMargin   528 non-null    float64
 47  right_leftMargin     528 non-null    float64
 48  right_rightMargin    528 non-null    float64
 49  right_wordPosition   528 non-null    float64
 50  right_txt            528 non-null    object
 51  bottom_startX        72 non-null     float64
 52  bottom_startY        72 non-null     float64
 53  bottom_endX          72 non-null     float64
 54  bottom_endY          72 non-null     float64
 55  bottom_w             72 non-null     float64
 56  bottom_h             72 non-null     float64
 57  bottom_fntSize       72 non-null     float64
 58  bottom_txtColor      72 non-null     float64
 59  bottom_txtFnt        72 non-null     object
 60  bottom_topMargin     72 non-null     float64
 61  bottom_bottomMargin  72 non-null     float64
 62  bottom_leftMargin    72 non-null     float64
 63  bottom_rightMargin   72 non-null     float64
 64  bottom_wordPosition  72 non-null     float64
 65  bottom_txt           72 non-null     object
 66  top_startX           72 non-null     float64
 67  top_startY           72 non-null     float64
 68  top_endX             72 non-null     float64
 69  top_endY             72 non-null     float64
 70  top_w                72 non-null     float64
 71  top_h                72 non-null     float64
 72  top_fntSize          72 non-null     float64
 73  top_txtColor         72 non-null     float64
 74  top_txtFnt           72 non-null     object
 75  top_topMargin        72 non-null     float64
 76  top_bottomMargin     72 non-null     float64
 77  top_leftMargin       72 non-null     float64
 78  top_rightMargin      72 non-null     float64
 79  top_wordPosition     72 non-null     float64
 80  top_txt              72 non-null     object
 81  txt                  621 non-null    object
dtypes: float64(63), int64(8), object(11)
memory usage: 398.0+ KB

In [6]:
data['startX']=data['startX'].apply(np.floor)
data1['startX']=data['startX'].apply(np.floor)


data['endX']=data['endX'].apply(np.ceil)
data1['endX']=data['endX'].apply(np.ceil)



data['startY']=data['startY'].apply(np.ceil)
data1['startY']=data['startY'].apply(np.ceil)



data['endY']=data['endY'].apply(np.ceil)
data1['endY']=data['endY'].apply(np.ceil)


data['w']=data['endX']-data['startX']
data1['w']=data['endX']-data['startX']



data['h']=data['endY']-data['startY']
data1['h']=data['endY']-data['startY']

In [7]:
data.loc[data['txtColor'] == (-16777216), 'txtColor'] = -1
data1.loc[data['txtColor'] == (-16777216), 'txtColor'] = -1
data.loc[data['txtColor'] == (-16777216), 'txtColor'] = -1
data1.loc[data['txtColor'] == (-16777216), 'txtColor'] = -1

In [8]:
data['label'] = data['label'].fillna('undefined')

In [9]:
data.drop('txt',inplace=True,axis=1)
data1.drop('txt',inplace=True,axis=1)

In [10]:
data.shape

(1987, 82)

In [11]:
data1.shape

(621, 81)

In [12]:
data.drop('docName',inplace=True,axis=1)
data1.drop('docName',inplace=True,axis=1)
data.drop('top_txt',inplace=True,axis=1)
data.drop('bottom_txt',inplace=True,axis=1)
data.drop('right_txt',inplace=True,axis=1)
data.drop('left_txt',inplace=True,axis=1)
data1.drop('top_txt',inplace=True,axis=1)
data1.drop('bottom_txt',inplace=True,axis=1)
data1.drop('right_txt',inplace=True,axis=1)
data1.drop('left_txt',inplace=True,axis=1)

In [13]:
data.shape

(1987, 77)

In [14]:
data1.shape

(621, 76)

In [15]:
data['top_wordPosition'] = data['top_wordPosition'].fillna(-1)
data['top_rightMargin'] = data['top_rightMargin'].fillna(-1)
data['top_leftMargin'] = data['top_leftMargin'].fillna(-1)
data['top_bottomMargin'] = data['top_bottomMargin'].fillna(-1)
data['top_topMargin'] = data['top_topMargin'].fillna(-1)
data['top_h'] = data['top_h'].fillna(-1)
data['top_w'] = data['top_w'].fillna(-1)
data['top_endY'] = data['top_endY'].fillna(-1)
data['top_endX'] = data['top_endX'].fillna(-1)
data['top_startY'] = data['top_startY'].fillna(-1)
data['top_startX'] = data['top_startX'].fillna(-1)
data['bottom_wordPosition'] = data['bottom_wordPosition'].fillna(-1)
data['bottom_rightMargin'] = data['bottom_rightMargin'].fillna(-1)
data['bottom_leftMargin'] = data['bottom_leftMargin'].fillna(-1)
data['bottom_bottomMargin'] = data['bottom_bottomMargin'].fillna(-1)
data['bottom_topMargin'] = data['bottom_topMargin'].fillna(-1)
data['bottom_h'] = data['bottom_h'].fillna(-1)
data['bottom_w'] = data['bottom_w'].fillna(-1)
data['bottom_endY'] = data['bottom_endY'].fillna(-1)
data['bottom_endX'] = data['bottom_endX'].fillna(-1)
data['bottom_startY'] = data['bottom_startY'].fillna(-1)
data['bottom_startX'] = data['bottom_startX'].fillna(-1)
data['right_wordPosition'] = data['right_wordPosition'].fillna(-1)
data['right_rightMargin'] = data['right_rightMargin'].fillna(-1)
data['right_leftMargin'] = data['right_leftMargin'].fillna(-1)
data['right_bottomMargin'] = data['right_bottomMargin'].fillna(-1)
data['right_topMargin'] = data['right_topMargin'].fillna(0)
data['right_h'] = data['right_h'].fillna(-1)
data['right_w'] = data['right_w'].fillna(-1)
data['right_endY'] = data['right_endY'].fillna(-1)
data['right_endX'] = data['right_endX'].fillna(-1)
data['right_startY'] = data['right_startY'].fillna(-1)
data['right_startX'] = data['right_startX'].fillna(-1)
data['left_wordPosition'] = data['left_wordPosition'].fillna(-1)
data['left_rightMargin'] = data['left_rightMargin'].fillna(-1)
data['left_leftMargin'] = data['left_leftMargin'].fillna(-1)
data['left_bottomMargin'] = data['left_bottomMargin'].fillna(-1)
data['left_topMargin'] = data['left_topMargin'].fillna(-1)
data['left_h'] = data['left_h'].fillna(-1)
data['left_w'] = data['left_w'].fillna(-1)
data['left_endY'] = data['left_endY'].fillna(-1)
data['left_endX'] = data['left_endX'].fillna(-1)
data['left_startY'] = data['left_startY'].fillna(-1)
data['left_startX'] = data['left_startX'].fillna(-1)






data1['top_wordPosition'] = data['top_wordPosition'].fillna(-1)
data1['top_rightMargin'] = data['top_rightMargin'].fillna(-1)
data1['top_leftMargin'] = data['top_leftMargin'].fillna(-1)
data1['top_bottomMargin'] = data['top_bottomMargin'].fillna(-1)
data1['top_topMargin'] = data['top_topMargin'].fillna(0)
data1['top_h'] = data['top_h'].fillna(-1)
data1['top_w'] = data['top_w'].fillna(-1)
data1['top_endY'] = data['top_endY'].fillna(-1)
data1['top_endX'] = data['top_endX'].fillna(-1)
data1['top_startY'] = data['top_startY'].fillna(-1)
data1['top_startX'] = data['top_startX'].fillna(-1)
data1['bottom_wordPosition'] = data['bottom_wordPosition'].fillna(-1)
data1['bottom_rightMargin'] = data['bottom_rightMargin'].fillna(-1)
data1['bottom_leftMargin'] = data['bottom_leftMargin'].fillna(-1)
data1['bottom_bottomMargin'] = data['bottom_bottomMargin'].fillna(-1)
data1['bottom_topMargin'] = data['bottom_topMargin'].fillna(-1)
data1['bottom_h'] = data['bottom_h'].fillna(-1)
data1['bottom_w'] = data['bottom_w'].fillna(-1)
data1['bottom_endY'] = data['bottom_endY'].fillna(-1)
data1['bottom_endX'] = data['bottom_endX'].fillna(-1)
data1['bottom_startY'] = data['bottom_startY'].fillna(-1)
data1['bottom_startX'] = data['bottom_startX'].fillna(-1)
data1['right_wordPosition'] = data['right_wordPosition'].fillna(-1)
data1['right_rightMargin'] = data['right_rightMargin'].fillna(-1)
data1['right_leftMargin'] = data['right_leftMargin'].fillna(-1)
data1['right_bottomMargin'] = data['right_bottomMargin'].fillna(-1)
data1['right_topMargin'] = data['right_topMargin'].fillna(-1)
data1['right_h'] = data['right_h'].fillna(-1)
data1['right_w'] = data['right_w'].fillna(-1)
data1['right_endY'] = data['right_endY'].fillna(-1)
data1['right_endX'] = data['right_endX'].fillna(-1)
data1['right_startY'] = data['right_startY'].fillna(-1)
data1['right_startX'] = data['right_startX'].fillna(-1)
data1['left_wordPosition'] = data['left_wordPosition'].fillna(-1)
data1['left_rightMargin'] = data['left_rightMargin'].fillna(-1)
data1['left_leftMargin'] = data['left_leftMargin'].fillna(-1)
data1['left_bottomMargin'] = data['left_bottomMargin'].fillna(-1)
data1['left_topMargin'] = data['left_topMargin'].fillna(-1)
data1['left_h'] = data['left_h'].fillna(-1)
data1['left_w'] = data['left_w'].fillna(-1)
data1['left_endY'] = data['left_endY'].fillna(-1)
data1['left_endX'] = data['left_endX'].fillna(-1)
data1['left_startY'] = data['left_startY'].fillna(-1)
data1['left_startX'] = data['left_startX'].fillna(-1)



data['txtFnt'] = data['txtFnt'].fillna('-1')
data['left_txtFnt'] = data['left_txtFnt'].fillna('-1')
data['right_txtFnt'] = data['right_txtFnt'].fillna('-1')
data['bottom_txtFnt'] = data['bottom_txtFnt'].fillna('-1')
data['top_txtFnt'] = data['top_txtFnt'].fillna('-1')


data1['txtFnt'] = data['txtFnt'].fillna('-1')
data1['left_txtFnt'] = data['left_txtFnt'].fillna('-1')
data1['right_txtFnt'] = data['right_txtFnt'].fillna('-1')
data1['bottom_txtFnt'] = data['bottom_txtFnt'].fillna('-1')
data1['top_txtFnt'] = data['top_txtFnt'].fillna('-1')


data1['left_fntSize'] = data1['left_fntSize'].fillna(-1)
data1['left_txtColor'] = data1['left_txtColor'].fillna(-1)
data1['right_fntSize'] = data1['right_fntSize'].fillna(-1)
data1['right_txtColor'] = data1['right_txtColor'].fillna(-1)
data1['bottom_fntSize'] = data1['bottom_fntSize'].fillna(-1)
data1['bottom_txtColor'] = data1['bottom_txtColor'].fillna(-1)
data1['top_fntSize'] = data1['top_fntSize'].fillna(-1)
data1['top_txtColor'] = data1['top_txtColor'].fillna(-1)

In [16]:
data.shape

(1987, 77)

In [17]:
data1.shape

(621, 76)

In [18]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1987 entries, 0 to 1986
Data columns (total 77 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   pgNo                 1987 non-null   int64
 1   startX               1987 non-null   float64
 2   startY               1987 non-null   float64
 3   endX                 1987 non-null   float64
 4   endY                 1987 non-null   float64
 5   w                    1987 non-null   float64
 6   h                    1987 non-null   float64
 7   fntSize              1987 non-null   float64
 8   txtColor             1987 non-null   int64
 9   txtFnt               1987 non-null   object
 10  pgW                  1987 non-null   int64
 11  pgH                  1987 non-null   int64
 12  topMargin            1987 non-null   float64
 13  bottomMargin         1987 non-null   float64
 14  leftMargin           1987 non-null   float64
 15  rightMargin          1987 non-null   float64
 16  lSize                1987 non-null   int64
 17  lnNo                 1987 non-null   int64
 18  lWhiteSpaces         1987 non-null   int64
 19  wordPosition         1987 non-null   int64
 20  left_startX          1987 non-null   float64
 21  left_startY          1987 non-null   float64
 22  left_endX            1987 non-null   float64
 23  left_endY            1987 non-null   float64
 24  left_w               1987 non-null   float64
 25  left_h               1987 non-null   float64
 26  left_fntSize         1650 non-null   float64
 27  left_txtColor        1650 non-null   float64
 28  left_txtFnt          1987 non-null   object
 29  left_topMargin       1987 non-null   float64
 30  left_bottomMargin    1987 non-null   float64
 31  left_leftMargin      1987 non-null   float64
 32  left_rightMargin     1987 non-null   float64
 33  left_wordPosition    1987 non-null   float64
 34  right_startX         1987 non-null   float64
 35  right_startY         1987 non-null   float64
 36  right_endX           1987 non-null   float64
 37  right_endY           1987 non-null   float64
 38  right_w              1987 non-null   float64
 39  right_h              1987 non-null   float64
 40  right_fntSize        1650 non-null   float64
 41  right_txtColor       1650 non-null   float64
 42  right_txtFnt         1987 non-null   object
 43  right_topMargin      1987 non-null   float64
 44  right_bottomMargin   1987 non-null   float64
 45  right_leftMargin     1987 non-null   float64
 46  right_rightMargin    1987 non-null   float64
 47  right_wordPosition   1987 non-null   float64
 48  bottom_startX        1987 non-null   float64
 49  bottom_startY        1987 non-null   float64
 50  bottom_endX          1987 non-null   float64
 51  bottom_endY          1987 non-null   float64
 52  bottom_w             1987 non-null   float64
 53  bottom_h             1987 non-null   float64
 54  bottom_fntSize       303 non-null    float64
 55  bottom_txtColor      303 non-null    float64
 56  bottom_txtFnt        1987 non-null   object
 57  bottom_topMargin     1987 non-null   float64
 58  bottom_bottomMargin  1987 non-null   float64
 59  bottom_leftMargin    1987 non-null   float64
 60  bottom_rightMargin   1987 non-null   float64
 61  bottom_wordPosition  1987 non-null   float64
 62  top_startX           1987 non-null   float64
 63  top_startY           1987 non-null   float64
 64  top_endX             1987 non-null   float64
 65  top_endY             1987 non-null   float64
 66  top_w                1987 non-null   float64
 67  top_h                1987 non-null   float64
 68  top_fntSize          303 non-null    float64
 69  top_txtColor         303 non-null    float64
 70  top_txtFnt           1987 non-null   object
 71  top_topMargin        1987 non-null   float64
 72  top_bottomMargin     1987 non-null   float64
 73  top_leftMargin       1987 non-null   float64
 74  top_rightMargin      1987 non-null   float64
 75  top_wordPosition     1987 non-null   float64
 76  label                1987 non-null   object
dtypes: float64(63), int64(8), object(6)
memory usage: 1.2+ MB

In [19]:
color=data['txtFnt'].unique()
color_lable={}
#print(dict(list(enumerate(color))))
for i in range(len(color)):
    color_lable[color[i]]=i
data['txtFnt']=data['txtFnt'].map(color_lable)




color_left=data['left_txtFnt'].unique()
color_lable_left={}
#print(dict(list(enumerate(color))))
for i in range(len(color_left)):
    color_lable_left[color_left[i]]=i
data['left_txtFnt']=data['left_txtFnt'].map(color_lable_left)

 
color_right=data['right_txtFnt'].unique()
color_lable_right={}
#print(dict(list(enumerate(color))))
for i in range(len(color_right)):
    color_lable_right[color_right[i]]=i
data['right_txtFnt']=data['right_txtFnt'].map(color_lable_right)






#data1
color1=data1['txtFnt'].unique()
color_lable1={}
#print(dict(list(enumerate(color))))
for i in range(len(color1)):
    color_lable1[color1[i]]=i
data1['txtFnt']=data1['txtFnt'].map(color_lable1)




color_left1=data1['left_txtFnt'].unique()
color_lable_left1={}
#print(dict(list(enumerate(color))))
for i in range(len(color_left1)):
    color_lable_left1[color_left1[i]]=i
data1['left_txtFnt']=data1['left_txtFnt'].map(color_lable_left1)

 
color_right1=data1['right_txtFnt'].unique()
color_lable_right1={}
#print(dict(list(enumerate(color))))
for i in range(len(color_right1)):
    color_lable_right1[color_right1[i]]=i
data1['right_txtFnt']=data1['right_txtFnt'].map(color_lable_right1)

In [20]:
color_bottom=data['bottom_txtFnt'].unique()
color_lable_bottom={}
#print(dict(list(enumerate(color))))
for i in range(len(color_bottom)):
    color_lable_bottom[color_bottom[i]]=i
data['bottom_txtFnt']=data['bottom_txtFnt'].map(color_lable_bottom)




color_bottom1=data1['bottom_txtFnt'].unique()
color_lable_bottom1={}
#print(dict(list(enumerate(color))))
for i in range(len(color_bottom1)):
    color_lable_bottom1[color_bottom1[i]]=i
data1['bottom_txtFnt']=data1['bottom_txtFnt'].map(color_lable_bottom1)


color_top=data['top_txtFnt'].unique()
color_lable_top={}
#print(dict(list(enumerate(color))))
for i in range(len(color_top)):
    color_lable_top[color_top[i]]=i
data['top_txtFnt']=data['top_txtFnt'].map(color_lable_top)



color_top1=data1['top_txtFnt'].unique()
color_lable_top1={}
#print(dict(list(enumerate(color))))
for i in range(len(color_top1)):
    color_lable_top1[color_top1[i]]=i
data1['top_txtFnt']=data1['top_txtFnt'].map(color_lable_top1)

In [21]:
print(data1.select_dtypes(include=['object']))
print(data.select_dtypes(include=['object']))

Empty DataFrame
Columns: []
Index: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, ...]

[621 rows x 0 columns]
          label
0          Name
1          Name
2          Name
3          Name
4          Name
...         ...
1982  undefined
1983  undefined
1984  undefined
1985  undefined
1986  undefined

[1987 rows x 1 columns]

In [22]:
X = data.iloc[:, :-1].values
y = data.iloc[:, -1].values

In [23]:
data1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 621 entries, 0 to 620
Data columns (total 76 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   pgNo                 621 non-null    int64
 1   startX               621 non-null    float64
 2   startY               621 non-null    float64
 3   endX                 621 non-null    float64
 4   endY                 621 non-null    float64
 5   w                    621 non-null    float64
 6   h                    621 non-null    float64
 7   fntSize              621 non-null    float64
 8   txtColor             621 non-null    int64
 9   txtFnt               621 non-null    int64
 10  pgW                  621 non-null    int64
 11  pgH                  621 non-null    int64
 12  topMargin            621 non-null    float64
 13  bottomMargin         621 non-null    float64
 14  leftMargin           621 non-null    float64
 15  rightMargin          621 non-null    float64
 16  lSize                621 non-null    int64
 17  lnNo                 621 non-null    int64
 18  lWhiteSpaces         621 non-null    int64
 19  wordPosition         621 non-null    int64
 20  left_startX          621 non-null    float64
 21  left_startY          621 non-null    float64
 22  left_endX            621 non-null    float64
 23  left_endY            621 non-null    float64
 24  left_w               621 non-null    float64
 25  left_h               621 non-null    float64
 26  left_fntSize         621 non-null    float64
 27  left_txtColor        621 non-null    float64
 28  left_txtFnt          621 non-null    int64
 29  left_topMargin       621 non-null    float64
 30  left_bottomMargin    621 non-null    float64
 31  left_leftMargin      621 non-null    float64
 32  left_rightMargin     621 non-null    float64
 33  left_wordPosition    621 non-null    float64
 34  right_startX         621 non-null    float64
 35  right_startY         621 non-null    float64
 36  right_endX           621 non-null    float64
 37  right_endY           621 non-null    float64
 38  right_w              621 non-null    float64
 39  right_h              621 non-null    float64
 40  right_fntSize        621 non-null    float64
 41  right_txtColor       621 non-null    float64
 42  right_txtFnt         621 non-null    int64
 43  right_topMargin      621 non-null    float64
 44  right_bottomMargin   621 non-null    float64
 45  right_leftMargin     621 non-null    float64
 46  right_rightMargin    621 non-null    float64
 47  right_wordPosition   621 non-null    float64
 48  bottom_startX        621 non-null    float64
 49  bottom_startY        621 non-null    float64
 50  bottom_endX          621 non-null    float64
 51  bottom_endY          621 non-null    float64
 52  bottom_w             621 non-null    float64
 53  bottom_h             621 non-null    float64
 54  bottom_fntSize       621 non-null    float64
 55  bottom_txtColor      621 non-null    float64
 56  bottom_txtFnt        621 non-null    int64
 57  bottom_topMargin     621 non-null    float64
 58  bottom_bottomMargin  621 non-null    float64
 59  bottom_leftMargin    621 non-null    float64
 60  bottom_rightMargin   621 non-null    float64
 61  bottom_wordPosition  621 non-null    float64
 62  top_startX           621 non-null    float64
 63  top_startY           621 non-null    float64
 64  top_endX             621 non-null    float64
 65  top_endY             621 non-null    float64
 66  top_w                621 non-null    float64
 67  top_h                621 non-null    float64
 68  top_fntSize          621 non-null    float64
 69  top_txtColor         621 non-null    float64
 70  top_txtFnt           621 non-null    int64
 71  top_topMargin        621 non-null    float64
 72  top_bottomMargin     621 non-null    float64
 73  top_leftMargin       621 non-null    float64
 74  top_rightMargin      621 non-null    float64
 75  top_wordPosition     621 non-null    float64
dtypes: float64(63), int64(13)
memory usage: 368.8 KB

In [24]:
data.select_dtypes(include=['object'])

          label
0          Name
1          Name
2          Name
3          Name
4          Name
...         ...
1982  undefined
1983  undefined
1984  undefined
1985  undefined
1986  undefined

[1987 rows x 1 columns]

In [25]:
#from sklearn.compose import ColumnTransformer
#from sklearn.preprocessing import OneHotEncoder
#ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [9])], remainder='passthrough')
#X = np.array(ct.fit_transform(X))

In [26]:
#ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [28])], remainder='passthrough')
#X = np.array(ct.fit_transform(X))

In [27]:
#ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [56])], remainder='passthrough')
#X = np.array(ct.fit_transform(X))

In [28]:
#ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [70])], remainder='passthrough')
#X = np.array(ct.fit_transform(X))

In [29]:
#ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [42])], remainder='passthrough')
#X = np.array(ct.fit_transform(X))

In [30]:
#Error encountered 

#ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [9])], remainder='passthrough')
#data1 = np.array(ct.fit_transform(data1))


#ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [28])], remainder='passthrough')
#data1 = np.array(ct.fit_transform(data1))


#ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [56])], remainder='passthrough')
#data1 = np.array(ct.fit_transform(data1))


#ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [70])], remainder='passthrough')
#data1 = np.array(ct.fit_transform(data1))

#ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [42])], remainder='passthrough')
#data1 = np.array(ct.fit_transform(data1))

In [31]:
X.shape

(1987, 76)

In [32]:
data1.shape

(621, 76)

In [33]:
data.select_dtypes(include=['object'])

          label
0          Name
1          Name
2          Name
3          Name
4          Name
...         ...
1982  undefined
1983  undefined
1984  undefined
1985  undefined
1986  undefined

[1987 rows x 1 columns]

In [34]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1987 entries, 0 to 1986
Data columns (total 77 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   pgNo                 1987 non-null   int64
 1   startX               1987 non-null   float64
 2   startY               1987 non-null   float64
 3   endX                 1987 non-null   float64
 4   endY                 1987 non-null   float64
 5   w                    1987 non-null   float64
 6   h                    1987 non-null   float64
 7   fntSize              1987 non-null   float64
 8   txtColor             1987 non-null   int64
 9   txtFnt               1987 non-null   int64
 10  pgW                  1987 non-null   int64
 11  pgH                  1987 non-null   int64
 12  topMargin            1987 non-null   float64
 13  bottomMargin         1987 non-null   float64
 14  leftMargin           1987 non-null   float64
 15  rightMargin          1987 non-null   float64
 16  lSize                1987 non-null   int64
 17  lnNo                 1987 non-null   int64
 18  lWhiteSpaces         1987 non-null   int64
 19  wordPosition         1987 non-null   int64
 20  left_startX          1987 non-null   float64
 21  left_startY          1987 non-null   float64
 22  left_endX            1987 non-null   float64
 23  left_endY            1987 non-null   float64
 24  left_w               1987 non-null   float64
 25  left_h               1987 non-null   float64
 26  left_fntSize         1650 non-null   float64
 27  left_txtColor        1650 non-null   float64
 28  left_txtFnt          1987 non-null   int64
 29  left_topMargin       1987 non-null   float64
 30  left_bottomMargin    1987 non-null   float64
 31  left_leftMargin      1987 non-null   float64
 32  left_rightMargin     1987 non-null   float64
 33  left_wordPosition    1987 non-null   float64
 34  right_startX         1987 non-null   float64
 35  right_startY         1987 non-null   float64
 36  right_endX           1987 non-null   float64
 37  right_endY           1987 non-null   float64
 38  right_w              1987 non-null   float64
 39  right_h              1987 non-null   float64
 40  right_fntSize        1650 non-null   float64
 41  right_txtColor       1650 non-null   float64
 42  right_txtFnt         1987 non-null   int64
 43  right_topMargin      1987 non-null   float64
 44  right_bottomMargin   1987 non-null   float64
 45  right_leftMargin     1987 non-null   float64
 46  right_rightMargin    1987 non-null   float64
 47  right_wordPosition   1987 non-null   float64
 48  bottom_startX        1987 non-null   float64
 49  bottom_startY        1987 non-null   float64
 50  bottom_endX          1987 non-null   float64
 51  bottom_endY          1987 non-null   float64
 52  bottom_w             1987 non-null   float64
 53  bottom_h             1987 non-null   float64
 54  bottom_fntSize       303 non-null    float64
 55  bottom_txtColor      303 non-null    float64
 56  bottom_txtFnt        1987 non-null   int64
 57  bottom_topMargin     1987 non-null   float64
 58  bottom_bottomMargin  1987 non-null   float64
 59  bottom_leftMargin    1987 non-null   float64
 60  bottom_rightMargin   1987 non-null   float64
 61  bottom_wordPosition  1987 non-null   float64
 62  top_startX           1987 non-null   float64
 63  top_startY           1987 non-null   float64
 64  top_endX             1987 non-null   float64
 65  top_endY             1987 non-null   float64
 66  top_w                1987 non-null   float64
 67  top_h                1987 non-null   float64
 68  top_fntSize          303 non-null    float64
 69  top_txtColor         303 non-null    float64
 70  top_txtFnt           1987 non-null   int64
 71  top_topMargin        1987 non-null   float64
 72  top_bottomMargin     1987 non-null   float64
 73  top_leftMargin       1987 non-null   float64
 74  top_rightMargin      1987 non-null   float64
 75  top_wordPosition     1987 non-null   float64
 76  label                1987 non-null   object
dtypes: float64(63), int64(13), object(1)
memory usage: 1.2+ MB

In [35]:
data

,pgNo,startX,startY,endX,endY,w,h,fntSize,txtColor,txtFnt,...,top_h,top_fntSize,top_txtColor,top_txtFnt,top_topMargin,top_bottomMargin,top_leftMargin,top_rightMargin,top_wordPosition,label
0,1,74.0,70.0,159.0,81.0,85.0,11.0,14.6832,-1,0,...,-1.0,NaN,NaN,0,-1.0,-1.0,-1.0,-1.0,-1.0,Name
1,1,163.0,70.0,176.0,81.0,13.0,11.0,14.6832,-1,0,...,-1.0,NaN,NaN,0,-1.0,-1.0,-1.0,-1.0,-1.0,Name
2,1,180.0,70.0,284.0,81.0,104.0,11.0,14.6832,-1,0,...,-1.0,NaN,NaN,0,-1.0,-1.0,-1.0,-1.0,-1.0,Name
3,1,288.0,70.0,369.0,81.0,81.0,11.0,14.6832,-1,0,...,-1.0,NaN,NaN,0,-1.0,-1.0,-1.0,-1.0,-1.0,Name
4,1,378.0,70.0,433.0,81.0,55.0,11.0,14.6832,-1,0,...,-1.0,NaN,NaN,0,-1.0,-1.0,-1.0,-1.0,-1.0,Name
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1982,1,395.0,1516.0,439.0,1522.0,44.0,6.0,9.7500,-1,11,...,-1.0,NaN,NaN,0,-1.0,-1.0,-1.0,-1.0,-1.0,undefined
1983,1,441.0,1516.0,461.0,1522.0,20.0,6.0,9.7500,-1,11,...,-1.0,NaN,NaN,0,-1.0,-1.0,-1.0,-1.0,-1.0,undefined
1984,1,463.0,1516.0,495.0,1522.0,32.0,6.0,9.7500,-1,11,...,-1.0,NaN,NaN,0,-1.0,-1.0,-1.0,-1.0,-1.0,undefined
1985,1,497.0,1516.0,541.0,1522.0,44.0,6.0,9.7500,-1,11,...,-1.0,NaN,NaN,0,-1.0,-1.0,-1.0,-1.0,-1.0,undefined
1986,1,543.0,1516.0,634.0,1522.0,91.0,6.0,9.7500,-1,11,...,-1.0,NaN,NaN,0,-1.0,-1.0,-1.0,-1.0,-1.0,undefined

In [36]:
data['left_fntSize'] = data['left_fntSize'].fillna(-1)
data['left_txtColor'] = data['left_txtColor'].fillna(-1)
data['right_fntSize'] = data['right_fntSize'].fillna(-1)
data['right_txtColor'] = data['right_txtColor'].fillna(-1)
data['bottom_fntSize'] = data['bottom_fntSize'].fillna(-1)
data['bottom_txtColor'] = data['bottom_txtColor'].fillna(-1)
data['top_fntSize'] = data['top_fntSize'].fillna(-1)
data['top_txtColor'] = data['top_txtColor'].fillna(-1)

In [37]:
nan_cols = [i for i in data.columns if data[i].isnull().any()]
print(nan_cols)

[]

In [38]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 1)

In [39]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)
data2_test=sc.transform(data1)#only scaling

In [40]:
y1=data['label'].unique()
y2={}
#print(dict(list(enumerate(color))))
for i in range(len(y1)):
    y2[y1[i]]=i
data['label']=data['label'].map(y2)


y1



from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)
y

array([4, 4, 4, ..., 5, 5, 5])

In [41]:
X_test.shape

(398, 76)

In [42]:
data2_test.shape

(621, 76)

In [43]:
from sklearn.ensemble import RandomForestClassifier
classifier = RandomForestClassifier(n_estimators = 10, criterion = 'entropy', random_state = 0)
classifier.fit(X_train, y_train)

ValueError: Input contains NaN, infinity or a value too large for dtype('float32').

In [73]:
np.isnan(X_train)

array([[False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       ...,
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False]])